publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true
  commit_messages:
    create: "netlify: Create {{collection}} '{{slug}}'"
    update: "netlify: Update {{collection}} '{{slug}}'"
    delete: "netlify: Delete {{collection}} '{{slug}}'"
    uploadMedia: "[skip ci] netlify: upload '{{path}}'"
    deleteMedia: "[skip ci] netlify: delete '{{path}}'"

media_folder: "/public/media_uploads"
public_folder: "/media_uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "/src/data/blog-posts"
    nested:
      depth: 100
    meta: { path: { widget: string, label: "Path", index_file: "index" } }
    create: true
    fields:
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string", default: "Bruno" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime", format: "YYYY-MM-DD", required: false }
      - { label: "Last Edition Date", name: "editDate", widget: "datetime", format: "YYYY-MM-DD", required: false }
      - { label: "Cover", name: "coverPath", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
    view_filters:
      - label: Drafts
        field: publishDate
        pattern: ""
    view_groups:
      - label: Date de publication
        field: publishDate
        pattern: \d{4}
      - label: Date de modification
        field: editDate
        pattern: \d{4}
      - label: Tags
        field: tags
